-- Add per-field source Sheet configuration and the error management table.
-- Run this once in the PostgreSQL/Supabase SQL editor.

ALTER TABLE public."GeneralSettings"
  ADD COLUMN IF NOT EXISTS "errorSheetUrls" text;

CREATE TABLE IF NOT EXISTS public."Errors" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field" varchar(50) NOT NULL,
  "title" varchar(255) NOT NULL,
  "chapter" varchar(100) NOT NULL,
  "errorType" varchar(30),
  "error" text NOT NULL,
  "note" text,
  "editor" varchar(255),
  "editorFreelancerId" integer,
  "fixCheck" boolean NOT NULL DEFAULT false,
  "sourceRow" integer,
  "sourceUrl" text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "Errors_field_fkey"
    FOREIGN KEY ("field") REFERENCES public."Fields" ("name") ON UPDATE CASCADE,
  CONSTRAINT "Errors_editor_fkey"
    FOREIGN KEY ("editorFreelancerId") REFERENCES public."Freelancer" ("fIld") ON DELETE SET NULL
);

ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "editorFreelancerId" integer;
ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "errorType" varchar(30);
ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "fixCheck" boolean NOT NULL DEFAULT false;
ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "sourceRow" integer;
ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "sourceUrl" text;
ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "createdAt" timestamptz NOT NULL DEFAULT now();
ALTER TABLE public."Errors" ADD COLUMN IF NOT EXISTS "updatedAt" timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS "Errors_field_idx" ON public."Errors" ("field");
CREATE INDEX IF NOT EXISTS "Errors_editor_idx" ON public."Errors" ("editorFreelancerId");

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."Errors" TO postgres;
