-- Store each freelancer's weekly/monthly capacity registration.
-- Run this once in the PostgreSQL/Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public."DeadlineRegistrations" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fIld" integer NOT NULL,
  "name" varchar(150) NOT NULL,
  "chaptersPerWeek" integer NOT NULL DEFAULT 0 CHECK ("chaptersPerWeek" >= 0),
  "chaptersPerMonth" integer NOT NULL DEFAULT 0 CHECK ("chaptersPerMonth" >= 0),
  "stability" varchar(100),
  "note" text,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "DeadlineRegistrations_freelancer_fkey"
    FOREIGN KEY ("fIld") REFERENCES public."Freelancer" ("fIld") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "DeadlineRegistrations_freelancer_unique"
  ON public."DeadlineRegistrations" ("fIld");

CREATE INDEX IF NOT EXISTS "DeadlineRegistrations_updated_idx"
  ON public."DeadlineRegistrations" ("updatedAt" DESC);

