-- Sample PostgreSQL schema and seed data for QC Webtoon.
-- Run this file in a disposable PostgreSQL/Supabase database.
-- The application expects the quoted table and column names below.
--
-- Required API mapping:
--   SUPABASE_TABLE_TASKS=SeriesList
--   SUPABASE_TABLE_FREELANCERS=Freelancer
--   SUPABASE_TABLE_QC=QC
--   SUPABASE_TABLE_ACCOUNTS=Accounts
--   SUPABASE_TABLE_DEADLINES=SeriesList
--   SUPABASE_TABLE_DIFFICULTY_LEVELS=DifficultyLevels
--   SUPABASE_TABLE_DIFFICULTY_PRICING=DifficultyPricing
--   SUPABASE_TABLE_BONUS_SETTINGS=BonusSettings
--   SUPABASE_TABLE_FIELDS=Fields
--   SUPABASE_TABLE_GENERAL_SETTINGS=GeneralSettings

BEGIN;

-- Remove the obsolete company-deadline table from an existing database.
DROP TABLE IF EXISTS "Companies";

-- Optional reset for a disposable database only. Uncomment if needed.
-- DROP TABLE IF EXISTS "SeriesList";
-- DROP TABLE IF EXISTS "QC";
-- DROP TABLE IF EXISTS "Freelancer";

CREATE TABLE IF NOT EXISTS "Freelancer" (
  "fIld" integer PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "email" varchar(255),
  "field" varchar(50),
  "fields" text[] NOT NULL DEFAULT ARRAY[]::text[],
  "note" text,
  "salary" numeric(14, 2),
  "imageQR" text
);

ALTER TABLE "Freelancer" ADD COLUMN IF NOT EXISTS "note" text;
ALTER TABLE "Freelancer" ADD COLUMN IF NOT EXISTS "salary" numeric(14, 2);
ALTER TABLE "Freelancer" ADD COLUMN IF NOT EXISTS "fields" text[];
UPDATE "Freelancer"
SET "fields" = CASE WHEN "field" IS NULL THEN ARRAY[]::text[] ELSE ARRAY["field"]::text[] END
WHERE "fields" IS NULL;
ALTER TABLE "Freelancer" ALTER COLUMN "fields" SET DEFAULT ARRAY[]::text[];
ALTER TABLE "Freelancer" ALTER COLUMN "fields" SET NOT NULL;
ALTER TABLE "Freelancer" DROP CONSTRAINT IF EXISTS "Freelancer_field_check";
ALTER TABLE "Freelancer" DROP CONSTRAINT IF EXISTS "Freelancer_fields_check";

CREATE TABLE IF NOT EXISTS "QC" (
  "qcId" integer PRIMARY KEY,
  "name" varchar(150) NOT NULL,
  "email" varchar(255),
  "imageQR" text
);

CREATE TABLE IF NOT EXISTS "Fields" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL UNIQUE,
  "guideUrl" text,
  "resourceUrl" text,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE "Fields" ADD COLUMN IF NOT EXISTS "guideUrl" text;
ALTER TABLE "Fields" ADD COLUMN IF NOT EXISTS "resourceUrl" text;

INSERT INTO "Fields" ("name") VALUES ('Japan'), ('Latin'), ('QC')
ON CONFLICT ("name") DO NOTHING;

CREATE TABLE IF NOT EXISTS "Accounts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) NOT NULL UNIQUE,
  "passwordHash" text NOT NULL,
  "passwordSalt" varchar(64) NOT NULL,
  "role" varchar(20) NOT NULL CHECK ("role" IN ('Admin', 'QC', 'Freelancer')),
  "displayName" varchar(150) NOT NULL,
  "email" varchar(255),
  "field" varchar(50),
  "fields" text[] NOT NULL DEFAULT ARRAY[]::text[],
  "freelancerId" integer,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "Accounts_freelancer_fkey"
    FOREIGN KEY ("freelancerId") REFERENCES "Freelancer" ("fIld") ON DELETE SET NULL
);

ALTER TABLE "Accounts" ADD COLUMN IF NOT EXISTS "freelancerId" integer;
ALTER TABLE "Accounts" ADD COLUMN IF NOT EXISTS "field" varchar(50);
ALTER TABLE "Accounts" ADD COLUMN IF NOT EXISTS "fields" text[];
UPDATE "Accounts"
SET "fields" = CASE WHEN "field" IS NULL THEN ARRAY[]::text[] ELSE ARRAY["field"]::text[] END
WHERE "fields" IS NULL;
ALTER TABLE "Accounts" ALTER COLUMN "fields" SET DEFAULT ARRAY[]::text[];
ALTER TABLE "Accounts" ALTER COLUMN "fields" SET NOT NULL;
ALTER TABLE "Accounts" DROP CONSTRAINT IF EXISTS "Accounts_field_check";
ALTER TABLE "Accounts" DROP CONSTRAINT IF EXISTS "Accounts_fields_check";
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'Accounts_freelancer_fkey'
  ) THEN
    ALTER TABLE "Accounts"
      ADD CONSTRAINT "Accounts_freelancer_fkey"
      FOREIGN KEY ("freelancerId") REFERENCES "Freelancer" ("fIld") ON DELETE SET NULL;
  END IF;
END $$;

-- Keep one account per Freelancer and synchronize account identity fields into Freelancer.
CREATE UNIQUE INDEX IF NOT EXISTS "Accounts_freelancer_unique"
  ON "Accounts" ("freelancerId")
  WHERE "freelancerId" IS NOT NULL;

CREATE OR REPLACE FUNCTION public.assign_freelancer_for_account()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  next_freelancer_id integer;
BEGIN
  IF NEW."role" IN ('Freelancer', 'QC') AND NEW."freelancerId" IS NULL THEN
    SELECT COALESCE(MAX("fIld"), 0) + 1 INTO next_freelancer_id FROM "Freelancer";
    INSERT INTO "Freelancer" ("fIld", "name", "email", "field", "fields")
    VALUES (next_freelancer_id, NEW."displayName", NEW."email", NEW."field", NEW."fields");
    NEW."freelancerId" := next_freelancer_id;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "Accounts_assign_freelancer" ON "Accounts";
CREATE TRIGGER "Accounts_assign_freelancer"
BEFORE INSERT OR UPDATE OF "role", "freelancerId"
ON "Accounts"
FOR EACH ROW
EXECUTE FUNCTION public.assign_freelancer_for_account();

CREATE OR REPLACE FUNCTION public.sync_account_to_freelancer()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."role" IN ('Freelancer', 'QC') AND NEW."freelancerId" IS NOT NULL THEN
    UPDATE "Freelancer"
    SET "name" = NEW."displayName",
        "email" = NEW."email",
        "field" = NEW."field",
        "fields" = NEW."fields"
    WHERE "fIld" = NEW."freelancerId";
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "Accounts_sync_freelancer" ON "Accounts";
CREATE TRIGGER "Accounts_sync_freelancer"
AFTER INSERT OR UPDATE OF "role", "displayName", "email", "field", "fields", "freelancerId"
ON "Accounts"
FOR EACH ROW
EXECUTE FUNCTION public.sync_account_to_freelancer();

-- Keep QC dropdown options synchronized with accounts that have role QC.
CREATE OR REPLACE FUNCTION public.sync_account_to_qc()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW."role" = 'QC' THEN
    INSERT INTO "QC" ("qcId", "name", "email")
    VALUES (NEW."id"::integer, NEW."displayName", NEW."email")
    ON CONFLICT ("qcId") DO UPDATE
      SET "name" = EXCLUDED."name", "email" = EXCLUDED."email";
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "Accounts_sync_qc" ON "Accounts";
CREATE TRIGGER "Accounts_sync_qc"
AFTER INSERT OR UPDATE OF "role", "displayName", "email"
ON "Accounts"
FOR EACH ROW
EXECUTE FUNCTION public.sync_account_to_qc();

CREATE TABLE IF NOT EXISTS "SeriesList" (
  "seriesId" integer NOT NULL,
  "chapterNumber" integer NOT NULL,
  "seriesName" varchar(255),
  "type" varchar(100),
  "statusRaw" varchar(100),
  "status" varchar(20),
  "doingStartedAt" timestamptz,
  "workDurationSeconds" integer NOT NULL DEFAULT 0,
  "urlSeries" text,
  "fIld" integer,
  "qcId" integer,
  "difficulty" varchar(50),
  "price" numeric(14, 2),
  "receivePrice" numeric(14, 2),
  "feedback" text,
  "task" varchar(100),
  "endTask" timestamptz,
  "submittedAt" timestamptz,
  "late" text NOT NULL DEFAULT '≤0h',
  "paymentApproved" boolean NOT NULL DEFAULT false,
  "completionPercent" integer NOT NULL DEFAULT 100,
  CONSTRAINT "SeriesList_pkey" PRIMARY KEY ("seriesId", "chapterNumber"),
  CONSTRAINT "SeriesList_freelancer_fkey"
    FOREIGN KEY ("fIld") REFERENCES "Freelancer" ("fIld"),
  CONSTRAINT "SeriesList_qc_fkey"
    FOREIGN KEY ("qcId") REFERENCES "QC" ("qcId")
);

ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "completionPercent" integer;
ALTER TABLE "SeriesList" ALTER COLUMN "difficulty" TYPE varchar(100);
ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "status" varchar(20);
ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "doingStartedAt" timestamptz;
ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "workDurationSeconds" integer;
ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "submittedAt" timestamptz;
ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "late" text;
ALTER TABLE "SeriesList" ADD COLUMN IF NOT EXISTS "paymentApproved" boolean;
ALTER TABLE "SeriesList" DROP COLUMN IF EXISTS "startTask";
UPDATE "SeriesList" SET "completionPercent" = 100 WHERE "completionPercent" IS NULL;
UPDATE "SeriesList" SET "workDurationSeconds" = 0 WHERE "workDurationSeconds" IS NULL;
UPDATE "SeriesList" SET "paymentApproved" = false WHERE "paymentApproved" IS NULL;
UPDATE "SeriesList" SET "late" = '≤0h' WHERE "late" IS NULL OR btrim("late") = '';
ALTER TABLE "SeriesList" ALTER COLUMN "completionPercent" SET DEFAULT 100;
ALTER TABLE "SeriesList" ALTER COLUMN "completionPercent" SET NOT NULL;
ALTER TABLE "SeriesList" ALTER COLUMN "workDurationSeconds" SET DEFAULT 0;
ALTER TABLE "SeriesList" ALTER COLUMN "workDurationSeconds" SET NOT NULL;
ALTER TABLE "SeriesList" ALTER COLUMN "paymentApproved" SET DEFAULT false;
ALTER TABLE "SeriesList" ALTER COLUMN "paymentApproved" SET NOT NULL;
ALTER TABLE "SeriesList" ALTER COLUMN "late" SET DEFAULT '≤0h';
ALTER TABLE "SeriesList" ALTER COLUMN "late" SET NOT NULL;

ALTER TABLE "SeriesList" DROP CONSTRAINT IF EXISTS "SeriesList_late_check";
ALTER TABLE "SeriesList"
  ADD CONSTRAINT "SeriesList_late_check"
  CHECK ("late" IN ('≤0h', '1~3h', '3~6h', '6~10h', '>10h'));

ALTER TABLE "SeriesList" DROP CONSTRAINT IF EXISTS "SeriesList_completionPercent_check";
ALTER TABLE "SeriesList"
  ADD CONSTRAINT "SeriesList_completionPercent_check"
  CHECK ("completionPercent" BETWEEN 0 AND 200);

ALTER TABLE "SeriesList" DROP CONSTRAINT IF EXISTS "SeriesList_status_check";
ALTER TABLE "SeriesList"
  ADD CONSTRAINT "SeriesList_status_check"
  CHECK ("status" IS NULL OR "status" IN ('doing', 'submitted', 'checking', 'fixing', 'done'));

ALTER TABLE "SeriesList" DROP CONSTRAINT IF EXISTS "SeriesList_workDurationSeconds_check";
ALTER TABLE "SeriesList"
  ADD CONSTRAINT "SeriesList_workDurationSeconds_check"
  CHECK ("workDurationSeconds" >= 0);

UPDATE "SeriesList"
SET "difficulty" = CASE "difficulty"
  WHEN 'Dễ' THEN 'Normal'
  WHEN 'Trung bình' THEN 'Medium'
  WHEN 'Khó' THEN 'Hard'
  ELSE "difficulty"
END
WHERE "difficulty" IN ('Dễ', 'Trung bình', 'Khó');

CREATE TABLE IF NOT EXISTS "DifficultyPricing" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field" varchar(50) NOT NULL,
  "difficulty" varchar(100) NOT NULL,
  "price" numeric(14, 2) NOT NULL DEFAULT 0 CHECK ("price" >= 0),
  CONSTRAINT "DifficultyPricing_field_difficulty_key" UNIQUE ("field", "difficulty")
);

ALTER TABLE "DifficultyPricing" ALTER COLUMN "difficulty" TYPE varchar(100);
ALTER TABLE "DifficultyPricing" DROP CONSTRAINT IF EXISTS "DifficultyPricing_field_check";

DO $$
DECLARE
  difficulty_check record;
BEGIN
  FOR difficulty_check IN
    SELECT conname
    FROM pg_constraint
    WHERE conrelid = 'public."DifficultyPricing"'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) ILIKE '%difficulty%'
  LOOP
    EXECUTE format('ALTER TABLE "DifficultyPricing" DROP CONSTRAINT %I', difficulty_check.conname);
  END LOOP;
END $$;

CREATE TABLE IF NOT EXISTS "DifficultyLevels" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "field" varchar(50) NOT NULL,
  "difficulty" varchar(100) NOT NULL,
  "color" varchar(7) NOT NULL DEFAULT '#64748B' CHECK ("color" ~ '^#[0-9A-Fa-f]{6}$'),
  "textColor" varchar(7) NOT NULL DEFAULT '#FFFFFF' CHECK ("textColor" ~ '^#[0-9A-Fa-f]{6}$'),
  CONSTRAINT "DifficultyLevels_field_difficulty_key" UNIQUE ("field", "difficulty")
);

ALTER TABLE "DifficultyLevels" DROP CONSTRAINT IF EXISTS "DifficultyLevels_field_check";
ALTER TABLE "DifficultyLevels" ADD COLUMN IF NOT EXISTS "textColor" varchar(7) NOT NULL DEFAULT '#FFFFFF';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public."DifficultyLevels"'::regclass
      AND conname = 'DifficultyLevels_textColor_check'
  ) THEN
    ALTER TABLE "DifficultyLevels"
      ADD CONSTRAINT "DifficultyLevels_textColor_check"
      CHECK ("textColor" ~ '^#[0-9A-Fa-f]{6}$');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "BonusSettings" (
  "id" integer PRIMARY KEY,
  "field" varchar(50),
  "taskThreshold" integer NOT NULL DEFAULT 20 CHECK ("taskThreshold" >= 0),
  "bonusPerTask" numeric(14, 2) NOT NULL DEFAULT 10000 CHECK ("bonusPerTask" >= 0),
  "qcDefaultPrice" numeric(14, 2) NOT NULL DEFAULT 0 CHECK ("qcDefaultPrice" >= 0)
);

ALTER TABLE "BonusSettings" ADD COLUMN IF NOT EXISTS "field" varchar(50);
ALTER TABLE "BonusSettings" ADD COLUMN IF NOT EXISTS "qcDefaultPrice" numeric(14, 2) NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS "BonusSettings_field_unique"
  ON "BonusSettings" ("field")
  WHERE "field" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "GeneralSettings" (
  "id" integer PRIMARY KEY,
  "googleSheetUrl" text,
  "googleSheetRange" text,
  "googleSheetTabs" text,
  "googleDriveFolders" text,
  "googleSheetAutoSync" boolean NOT NULL DEFAULT false,
  "googleSheetLastSyncedAt" timestamptz,
  "googleSheetLastSyncCount" integer NOT NULL DEFAULT 0,
  "googleSheetLastSyncError" text
);

ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetUrl" text;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetRange" text;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetTabs" text;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleDriveFolders" text;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetAutoSync" boolean NOT NULL DEFAULT false;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetLastSyncedAt" timestamptz;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetLastSyncCount" integer NOT NULL DEFAULT 0;
ALTER TABLE "GeneralSettings" ADD COLUMN IF NOT EXISTS "googleSheetLastSyncError" text;

-- Start with no configured difficulty prices/levels. Admin can create them from the Giá tiền tab.
DELETE FROM "DifficultyPricing"
WHERE "field" IN ('Latin', 'Japan', 'QC');

DELETE FROM "DifficultyLevels"
WHERE "field" IN ('Latin', 'Japan', 'QC');

CREATE INDEX IF NOT EXISTS "SeriesList_freelancer_idx" ON "SeriesList" ("fIld");
CREATE INDEX IF NOT EXISTS "SeriesList_qc_idx" ON "SeriesList" ("qcId");
CREATE INDEX IF NOT EXISTS "DifficultyPricing_field_idx" ON "DifficultyPricing" ("field");

-- The QC editor endpoint updates only the editable fields in SeriesList.
-- The sample backend connects as postgres, so this grant is explicit for testing.
GRANT SELECT, INSERT, UPDATE ON TABLE "SeriesList" TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "DifficultyPricing" TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "DifficultyLevels" TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "BonusSettings" TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "Accounts" TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "Fields" TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "GeneralSettings" TO postgres;

INSERT INTO "BonusSettings" ("id", "field", "taskThreshold", "bonusPerTask", "qcDefaultPrice") VALUES
  (1, NULL, 20, 10000, 0)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "BonusSettings" ("field", "taskThreshold", "bonusPerTask", "qcDefaultPrice")
SELECT "name", 20, 10000, 0
FROM "Fields"
WHERE "name" IN ('Japan', 'Latin', 'QC')
ON CONFLICT ("field") DO NOTHING;

INSERT INTO "GeneralSettings" ("id") VALUES
  (1)
ON CONFLICT ("id") DO NOTHING;

-- Initial login: username admin / password admin123. Change it after login.
INSERT INTO "Accounts" ("username", "passwordHash", "passwordSalt", "role", "displayName", "email")
VALUES (
  'admin',
  '7c43f80888aec4f243a0260d244acb67ec6cf57fbd24d638206bd49f858714c66d1f344dfc0fd966549384e2021176646919ef63add209a8201a7ee09fab58f1',
  'a1b2c3d4e5f60718293a4b5c6d7e8f90',
  'Admin',
  'Administrator',
  'admin@example.com'
)
ON CONFLICT ("username") DO NOTHING;

-- Member profiles are created automatically when an account with role
-- Freelancer or QC is created. Do not seed standalone/fake rows here.

UPDATE "SeriesList"
SET "receivePrice" = ROUND(("price" * "completionPercent") / 100, 2)
WHERE "price" IS NOT NULL;

COMMIT;
